server:
  port: 8094
  error:
    include-message: always

spring:
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:h2:mem:shoppingDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverName: org.h2.Driver
    platform: h2
    user: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true