server:
  port:
    8081

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          bootstrap: true
          default-label: main
          uri: C:\workspace\store
          searchPaths: config-data
  security:
    user:
      name: root
      password: s3cr3t
